server:
  port: 80

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

spring:
  datasource:
    url: jdbc:mysql://172.17.46.2:3306/test
    username: u_tpersonfin
    password: u_tpersonfin78@78M
  devtools:
    restart:
      enabled: true
      #设置重启的目录，添加那个目录的文件需要restart
      additional-paths: src/main/java
      # 默认配置下,热部署后总是报404
      poll-interval: 3000ms
      quiet-period: 2999ms

